version: "3.9"
name: contract-tracker

services:
  api:
    build: ./tracker-api
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/clauses.db

  app:
    build: ./tracker-app
    ports:
      - "4200:80"
    depends_on:
      - api
volumes:
  sqlite_data: